version: '3.8'

services:

  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3307"
    networks:
      - ms_network
    volumes:
      - ms_data_23:/var/lib/mysql

  adminer:
    image: adminer:latest
    container_name: adminer_container
    ports:
      - "8080:8080"
    networks:
      - ms_network

  ms1:
    image: altunb/repo1:ms-1
    container_name: ms1_container
    restart: always
    ports:
      - 8081:8081
    networks:
      - ms_network
    depends_on:
      - mysql
    environment:
      DB_CONNECTION_HOST: mysql_container
      DB_CONNECTION_PORT: 3307
      DB_USERNAME: root
      DB_PASSWORD: password

  ms2:
    image: altunb/repo1:ms-2
    container_name: ms2_container
    restart: always
    ports:
      - 8082:8082
    networks:
      - ms_network
    depends_on:
      - mysql
    environment:
      DB_CONNECTION_HOST: mysql_container
      DB_CONNECTION_PORT: 3307
      DB_USERNAME: root
      DB_PASSWORD: password

  reverse_proxy:
    image: nginx:latest
    hostname: proxy
    container_name: reverse_proxy
    restart: always
    networks:
      - ms_network
    ports:
      - 8000:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - ms1
      - ms2

volumes:
  ms_data_23:

networks:
  ms_network:
    driver: bridge